/* Generated by scripts/optimize-images.mjs. Do not edit by hand. */

export interface GeneratedImage {
  width: number;
  height: number;
  ratio: string;
  /** 24px WebP as a data URI, for the blur-up placeholder. */
  lqip: string;
}

export const GENERATED_IMAGES = {
  "home-hero": {
    "width": 1040,
    "height": 1300,
    "ratio": "4:5",
    "lqip": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAADwBQCdASoYAB4APxF4tlOsJyUiqAqpgCIJYwDCgBDhOW4L0TDv8AuQgw21E+qCvQmh9/9gMwgtQAD+2O9piXs3uufI2fCa5U3qrzSMRkXhoYFvnPfqpQ8Dqz54TuXKCIaV1hfail6g1l+0oa8R3qW3+i+w0aHsJTirp6vVRAput6MnFJ9dSR7FBhjliG+tA8IwxCJyHD4lmdX5zOZaXXR54JFS4skuoHIjOxiBsk/R9ZOnYqAAAA=="
  },
  "program-hypertrophy-foundations": {
    "width": 1200,
    "height": 900,
    "ratio": "4:3",
    "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAADwBACdASoYABIAPxGAt1WsJ6UjKAgBgCIJZwAAKvMgRjtipZsduYoiRt9GXT9aQAAA/tBxb2NcdWAUZvb4K2yeok8/UdNlUlv2loutCtsVKI9dXfHfENRlGKAnGNDMzO/qWXi7Pu/0futDgeqGlBeV4P7g5JcUBeMlW/PSIZRsl48UdiHIHCxO5bSdVFkyVLkpwTWAOigOeQKLzibN8L2pcI6G2IBd4JCAgQAA"
  },
  "program-posterior-chain": {
    "width": 1200,
    "height": 900,
    "ratio": "4:3",
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAQBQCdASoYABIAPxF6tVOsJ6UiqAqpgCIJZwAD5YjDSEKE9EYhHgrFrEWZbj3iA5uAAP3SOymjuYH+8XZPcCKK4zvX4pKZnOgbxJ30LSQR2c32OoRoZlw+IXGN/u16lN9xSx2g+9SfQeXxowpdlhB7vPu4yMUtv7SHdmVANmHDmCxBroWgpZjSE3OHN9ZY9TUp+I2lMwwAAA=="
  },
  "recipe-chicken-rice-bowl": {
    "width": 1280,
    "height": 720,
    "ratio": "16:9",
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoYAA4APxFysFAsJqSisAgBgCIJQBWABBqS43cLAuHwOKffAAD94aKBqYGfzIS5hts45qzaUyO7vSC5RZDl5nRuPH4kto8vb4Xam46P/cYvP/Ws+38PP6hhtnnLC6gDneWxSGYAvQTeDgAA"
  }
} as const satisfies Record<string, GeneratedImage>;

export type GeneratedImageId = keyof typeof GENERATED_IMAGES;

export function lqipFor(id: string): string | undefined {
  return (GENERATED_IMAGES as Record<string, GeneratedImage>)[id]?.lqip;
}
