/* Generated by scripts/optimize-images.mjs. Do not edit by hand. */

export interface GeneratedImage {
  width: number;
  height: number;
  ratio: string;
  /** 24px WebP as a data URI, for the blur-up placeholder. */
  lqip: string;
}

export const GENERATED_IMAGES = {
  "home-hero": {
    "width": 1040,
    "height": 1300,
    "ratio": "4:5",
    "lqip": "data:image/webp;base64,UklGRhIBAABXRUJQVlA4IAYBAACQBgCdASoYAB4APxF2s1KsJySisBgIAYAiCWcAzYXdI4HTOZW9LOtEizYmcpXc4hJG2L8iTD2Lre+x2QAAAMscWdKOqulGslo5bu+DKI5hfj+3nYUVAtIydBLiXe5SzrZlOki1UV1ze43E12O4LY+GTJLg5Ft8qiClVLeHjA/N7Os1RBbrFfyZ5CGuNSc/mKOGOSLN6zybz5sMnnfG+nwn661r9YrahyfWEdMbspMfgn7HCpOeqqxgPGF4CojiSh3U1XxgRwjpHcjNKdrUIkguyqr7Crnff6MBII6NJhUnAizAsAPgn1WHXBiCPyECQMO+w1FxvK4roJzTKJIi5Yc/RFg5gAAA"
  },
  "program-hypertrophy-foundations": {
    "width": 1200,
    "height": 900,
    "ratio": "4:3",
    "lqip": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAABQBQCdASoYABIAPxF8slQsJ6QjKAqpgCIJYwDImywTogJrpSXzmK1inQPxp7a54qqRdQAA4dQnajaU8t95XL231s/XoNWqfgYeCpGQ1VCEdLPTwfp0hHVEwCpfS8F2PVY6v7v71ay/ROWvALN4o3Q+pzU8ZHfGZtpHJXC/r6kVtnlLNj+Oh7NUCThTGoJlBLKxyRQ83W86dbExM17fJnfmL7r+HSksByD9UUz/ePEGslxRE/lQcyXL5uIORDaANTAAAA=="
  },
  "program-strength-base": {
    "width": 1200,
    "height": 900,
    "ratio": "4:3",
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADwBACdASoYABIAPxF+tlWsJ6SjKAgBgCIJQBibAiSZbUZaPWyv/rKk0Hg70/d9ZwAA/tvC38Ao0jDan49ZQ2xa3iML8Yn5aW16iatUVob/EEJrW8dCjoO+a6KDAy2nMcC2mBp9AtYcPS12SWHyGGDUOdbF7nPQYuXy3Z5KOEsKSIAAAAA="
  },
  "program-minimal-kit": {
    "width": 1200,
    "height": 900,
    "ratio": "4:3",
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAwBQCdASoYABIAPxGAt1WsJ6UjKAgBgCIJZQC/OBDe8ld8bDsJPVbTys2IN9dVdJbyAAD+aXFwz2duEaFeFmLl5AwXVlyR2XWh3JDBNw+M1/KVVrNWrVyoQy+SV4NLMvzxTdT7nB5po+QM+EQpj/N84/AL4BL6vuQTJQdxOe6mDbtn3sp9GJ6X+ggpVP8BYgCWLytdch/uFDycYxAAAA=="
  },
  "program-posterior-chain": {
    "width": 1200,
    "height": 900,
    "ratio": "4:3",
    "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAwBQCdASoYABIAPxF6tFQsJySjKAqpgCIJaADCgA/QXjFbr+vcJ99kDYFaWJAfIXTCoAD+3aJryYFGLJBKTXCHb0uoerBzg4MSgv/ll87GmG/Bxt0YnR1HMyEtJX3OzbW4e1nwJB+s85xuUlgLfHodiJS7GM1LGFCE2FfxoW5a+uUxbNrhiUpP8X5UU+Ter/EubXwtW33dPY/WjdhVwo4AAAA="
  },
  "program-push-pull-legs": {
    "width": 1200,
    "height": 900,
    "ratio": "4:3",
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAwBACdASoYABIAPxGAt1WsJ6UjKAgBgCIJQAAEq8yjOu5TrP5oa5f9xAAAyRHc6xyCqAa+siY8Uz355ntOlrnZdJ6KKlVs6A9FrAHXICBD0+x7aclJxuv/ZFnX66C4OAAcmB6tV2Hsjp9iYii4C7ObInvx0D8FnOKqJxcanhVV+2DmaSpdPW7pb9jtDmnNOZlEjkN80BDvD0AAAAA="
  },
  "program-recipe-pack": {
    "width": 1200,
    "height": 900,
    "ratio": "4:3",
    "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACQBQCdASoYABIAPxF+tlWsJ6SjKAgBgCIJQBkXF/gxocIXj8L6QVMaav0bNu579QNwwMtygAD+5+4OaOmabruJx0KTtqlcx2Dh0xq1n+Nqu7rQaqXLgPJKvjzVnWQOp8Z89iG3ZgO7Wkq9zpXKXFrwzkQvwY6XB4qc6u4h0x7kGu7j3yrE9R/9rqekFO29SfRm22srsnYO/j417A9yz8I43FZSsIjCFGCIEqYjjQAAAA=="
  },
  "recipe-shakshuka": {
    "width": 1280,
    "height": 720,
    "ratio": "16:9",
    "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBACdASoYAA4APxFysFAsJqSisAgBgCIJbACdH8At+0mkRVSOLiZx1zcOIAD+zYCeO+FH8r9wp3SZRBVrWWekvSaj+jf6aokMDS8wdhVMZyEWbIhFkv8NNPHteYNbnF35+MaZvnxRM3cpMsGenRqIRfyBRtGjArdzhuTglPbnxdDVy3q4vsorEUbf82W7p4q8ohUtCScrTPxFFGWzsGrBokVkdo3QAAA="
  },
  "recipe-chicken-rice-bowl": {
    "width": 1280,
    "height": 720,
    "ratio": "16:9",
    "lqip": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAADwBACdASoYAA4APxFwsFAsJiSisAgBgCIJbACdMoR3FfqjeAF3oAQOfghkEa+l64AA/lX2pP9WpwSM0oSiCh4mg+Nto4DCBane6jCi9araauq6qgA2IBaDUATLpQhwnW3CbxGmE7SRKf5tMbcSpKiltwo/MJcbtNew4FBBpYS1OpP98L5FsxkzWoPQbhxJF2QBE/wDcyz8sLE08RrOazlPQaCr/vH5lCq+PJneHiLjUPvSAAA="
  },
  "recipe-overnight-oats": {
    "width": 1280,
    "height": 720,
    "ratio": "16:9",
    "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAQBQCdASoYAA4APxFysFAsJqSisAgBgCIJZgCdMoMYA0c12tsPqLQ657P/ofdVOsgAAP7V66BNgJ8OlwjnR4R3h2QTm3kB0D8H7k4Fqt4nk6A2shad3RK6pSI/L7xh3oOOcji4EJrwlBwplmDyntZWI8QLCssjoufSaJiUIq1vjEjXQGKjSKYPewZt8Rnsh7FQKsOzfh/qYUZjxYIW150+sgA="
  },
  "starter-cover": {
    "width": 1200,
    "height": 800,
    "ratio": "3:2",
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoYABAAPxFwsFAsJiSisAgBgCIJZwDMHCP+StO3wL6OgcAA++5FueF+2fqddma+ctF9XBZc8veKPKb8uLBl7c87oWO5ezjNr9X8GcrMwNsvQlaORt7pAPesQzTWUse1gAA="
  }
} as const satisfies Record<string, GeneratedImage>;

export type GeneratedImageId = keyof typeof GENERATED_IMAGES;

export function lqipFor(id: string): string | undefined {
  return (GENERATED_IMAGES as Record<string, GeneratedImage>)[id]?.lqip;
}
