#!/usr/bin/env node
/**
 * sharp-based optimiser. Reads public/images/source/*, crops each to the ratio
 * declared in assets/manifest.json, and emits:
 *   src/assets/images/<slot>.jpg            master, consumed by <Image>
 *   public/images/opt/<slot>-<w>.avif|webp  standalone responsive sets
 *   src/assets/images/generated.ts          a typed map: dimensions + LQIP blur data
 *
 * Astro's <Image> also derives its own AVIF/WebP set from the master. The
 * standalone set exists so the pipeline is usable outside Astro (email, OG,
 * social) and so the LQIP values are checked into a typed module rather than
 * recomputed at render time.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const ROOT = path.resolve(import.meta.dirname, '..');
const manifest = JSON.parse(await fs.readFile(path.join(ROOT, 'assets/manifest.json'), 'utf8'));
const { masters, responsive, downloads, widths, formats, lqipWidth } = manifest.output;

await fs.mkdir(path.join(ROOT, masters), { recursive: true });
await fs.mkdir(path.join(ROOT, responsive), { recursive: true });

const map = {};
let done = 0;
let skipped = 0;

for (const slot of manifest.slots) {
  if (slot.blocked) { skipped += 1; continue; }
  if (!slot.path.startsWith('src/assets/images/')) continue;

  const input = path.join(ROOT, downloads, `${slot.id}.jpg`);
  if (!(await exists(input))) {
    console.log(`skip   ${slot.id} — no source file, renders as a flagged block`);
    skipped += 1;
    continue;
  }

  const [wRatio, hRatio] = slot.ratio.split(':').map(Number);
  const height = Math.round((slot.width * hRatio) / wRatio);

  const base = sharp(input).rotate();
  const master = path.join(ROOT, masters, `${slot.id}.jpg`);
  await base
    .clone()
    .resize(slot.width, height, { fit: 'cover', position: 'attention' })
    .jpeg({ quality: 84, mozjpeg: true, chromaSubsampling: '4:4:4' })
    .toFile(master);

  for (const width of widths) {
    if (width > slot.width) continue;
    const h = Math.round((width * hRatio) / wRatio);
    for (const format of formats) {
      const out = path.join(ROOT, responsive, `${slot.id}-${width}.${format}`);
      const pipeline = sharp(master).resize(width, h, { fit: 'cover' });
      await (format === 'avif'
        ? pipeline.avif({ quality: 55, effort: 4 })
        : pipeline.webp({ quality: 74 })
      ).toFile(out);
    }
  }

  // LQIP: a 24px-wide WebP inlined as a data URI, used as the CSS background
  // behind the image so the layout never paints an empty box.
  const lqip = await sharp(master)
    .resize(lqipWidth, Math.max(1, Math.round((lqipWidth * hRatio) / wRatio)))
    .webp({ quality: 30 })
    .toBuffer();

  map[slot.id] = {
    width: slot.width,
    height,
    ratio: slot.ratio,
    lqip: `data:image/webp;base64,${lqip.toString('base64')}`,
  };
  done += 1;
  console.log(`OK     ${slot.id} → ${slot.width}×${height} (+${widths.filter((w) => w <= slot.width).length * formats.length} variants)`);
}

const module = `/* Generated by scripts/optimize-images.mjs. Do not edit by hand. */

export interface GeneratedImage {
  width: number;
  height: number;
  ratio: string;
  /** 24px WebP as a data URI, for the blur-up placeholder. */
  lqip: string;
}

export const GENERATED_IMAGES = ${JSON.stringify(map, null, 2)} as const satisfies Record<string, GeneratedImage>;

export type GeneratedImageId = keyof typeof GENERATED_IMAGES;

export function lqipFor(id: string): string | undefined {
  return (GENERATED_IMAGES as Record<string, GeneratedImage>)[id]?.lqip;
}
`;
await fs.writeFile(path.join(ROOT, masters, 'generated.ts'), module);

console.log(`\n${done} optimised, ${skipped} left as flagged blocks → ${masters}/generated.ts`);

async function exists(p) { try { await fs.access(p); return true; } catch { return false; } }
